language: cpp
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - git submodule init && git submodule update
  - mkdir build
  - cd build
  - cmake .. && make
  - ./tests/Tests